version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
